### ISSUE TITLE
Use Perplexica's API

### ISSUE THREAD

**Issue by ItzCrazyKns** [simular-ai/Agent-S#10]
Great project, would like to let you know that there's an API for Perplexica now that you can make use of instead of scraping contents from the web app or using the web socket. You can read more over here: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/API/SEARCH.md

**Comment by eric-simu** [comment]
Thanks for the update! We will work on incorporating the API. Meanwhile, we welcome and appreciate open source contributions!
