### ISSUE TITLE
two bugs in code ?

### ISSUE THREAD

**Issue by fanxing82** [simular-ai/Agent-S#23]
1. agent_s/GraphSearchAgent.py
    Ln80:  "self.grounding_agent = OpenACIGroundingAgent()"
    but openaci/ubuntu/Grounding.py:  "def __init__(self, obs, top_app=None)",  required parameter “obs”

2. agent_s/DAGPlanner.py
    Ln313:   "self.active_apps = agent.get_current_applications(initial_observation)"
    method(get_current_applications) is not exist in the openaci/ubuntu/Grounding.py

**Comment by eric-simu** [comment]
Hi, we just refactored the codebase and fixed some bugs. can you try the new release?
