### ISSUE TITLE
NameError: name 'OpenACIGroundingAgent' is not defined

### ISSUE THREAD

**Issue by tezansahu** [simular-ai/Agent-S#6]
Getting `NameError: name 'OpenACIGroundingAgent' is not defined` on submitting a query on the CLI app

![image](https://github.com/user-attachments/assets/e2517bd0-97ec-41c0-9a84-7ae2e9bfc2a0)

**Comment by saa1605** [comment]
Hi @tezansahu, thank you for raising this issue. The import for OpenACIGroundingAgent is dependent on the openaci package being installed successfully. However, we currently support only MacOS and Linux for the OpenACI grounding agent. We will soon add Windows Support as well. If you wish to implement your own version for Windows before that, see the macos Grounding and UIElement packages (https://github.com/simular-ai/OpenACI/tree/main/openaci/macos) for reference.

**Comment by tezansahu** [comment]
Hello @saa1605 
Thanks a lot for the clarification.
Curious to know if this would work on WSL (Ubuntu 22.04), since you mentioned it supports MacOS & Linux.
Have you tried it? Any thoughts?

**Comment by jmanhype** [comment]
im on linux having same issues
